# Generated by Django 3.2.15 on 2022-08-05 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jsm_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='produto',
            name='destaque',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='produto',
            name='figura',
            field=models.ImageField(default='images/default.png', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='produto',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='jsm_app.categoria'),
            preserve_default=False,
        ),
    ]
