# Generated by Django 3.2.15 on 2022-08-11 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsm_app', '0003_pedido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('senha', models.CharField(max_length=64)),
            ],
        ),
    ]
