# Generated by Django 4.0.6 on 2022-08-17 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsm_app', '0007_alter_pedido_cliente_alter_pedido_produto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='ender',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
