# Generated by Django 4.0.6 on 2022-08-17 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jsm_app', '0008_usuario_ender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='ender',
        ),
    ]
