# Generated by Django 4.0.6 on 2022-08-17 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsm_app', '0009_remove_usuario_ender'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='ender',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
