# Generated by Django 4.0.6 on 2022-08-17 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsm_app', '0010_usuario_ender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='ender',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
